app = "maplemeta-web"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT = "8080"
  PGHOST = "db.okjrtyiucbywjhqgvxsd.supabase.co"
  PGPORT = "5432"
  PGDATABASE = "postgres"
  PGUSER = "postgres"
  PGSCHEMA = "public"
  APP_NAME = "Maple Meta Dashboard"
  PATCH_NOTE_BASE_PATH = ""
