# fly.toml app configuration file generated for maplemeta on 2026-03-04T07:21:42+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'maplemeta'
primary_region = 'sin'

[build]

[env]
  APP_NAME = 'Maple Meta Dashboard'
  PATCH_NOTE_BASE_PATH = ''
  PGDATABASE = 'postgres'
  PGPORT = '5432'
  PGSCHEMA = 'public'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
