services:
  - type: web
    name: maplemeta-web
    env: python
    region: singapore
    plan: free
    rootDir: .
    buildCommand: bash build.sh
    startCommand: bash start.sh
    envVars:
      - key: PGHOST
        value: db.okjrtyiucbywjhqgvxsd.supabase.co
      - key: PGPORT
        value: 5432
      - key: PGDATABASE
        value: postgres
      - key: PGUSER
        value: postgres
      - key: PGPASSWORD
        sync: false
      - key: PGSCHEMA
        value: public
      - key: APP_NAME
        value: Maple Meta Dashboard
      - key: SELF_PING_URL
        sync: false
      - key: PATCH_NOTE_BASE_PATH
        value: 
